Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.define "vm1" do |vm1|
      vm1.vm.box = "generic/ubuntu2204"
      vm1.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 4
      end
      vm1.vm.network "private_network", ip: "192.168.57.101"
      vm1.vm.provision "shell", privileged: false, reset: true do |s|
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo systemctl disable systemd-resolved
    sudo systemctl stop systemd-resolved
    sudo rm /etc/resolv.conf
    echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
  SHELL

end