Vagrant.configure("2") do |config|
    config.vm.define "vm1" do |vm1|
      vm1.vm.box = "generic/ubuntu2204"
      vm1.vm.provider "virtualbox" do |v|
        v.memory = 4096 
        v.cpus = 4
      end
      vm1.vm.network "private_network", ip: "192.168.57.101"
      vm1.vm.provision "shell", privileged: false, reset: true do |s|
      end
    end
  end