Vagrant.configure("2") do |config|
    # Configure router1
    config.vm.define "router1" do |router1|
        router1.vm.box = "generic/ubuntu2204"
        router1.vm.network "private_network", ip: "192.168.56.10"
        router1.vm.hostname = "router1"
        router1.vm.provision "shell", inline: <<-SHELL
        # Disable systemd-resolved and set static DNS
        sudo systemctl disable systemd-resolved
        sudo systemctl stop systemd-resolved
        sudo rm /etc/resolv.conf
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
    
        # Install FRR
        sudo apt-get update
        sudo apt-get install -y frr frr-doc
        sudo sysctl -w net.ipv4.ip_forward=1
        echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
        SHELL
    
        # router1.vm.synced_folder "./config/router1/etc/frr", "/etc/frr"
    
        router1.vm.provision "shell", inline: <<-SHELL

            sudo tee /etc/frr/frr.conf <<EOF
!
frr version 8.1
frr defaults traditional
hostname router1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65001
    bgp router-id 192.168.56.10
    neighbor 192.168.56.11 remote-as 65002
    !
    address-family ipv4 unicast
    network 192.168.56.0/24
    neighbor 192.168.56.11 soft-reconfiguration inbound
    exit-address-family
exit
!
end
EOF

            # Enable BGPD and restart FRR
            sudo sed -i 's/bgpd=no/bgpd=yes/' /etc/frr/daemons
            sudo systemctl restart frr
            # Check if FRR is active
            if ! systemctl is-active --quiet frr; then
                echo "FRR service did not start properly."
                exit 1
            fi
        SHELL
    
    end
  
  
    # Configure router2
    config.vm.define "router2" do |router2|
        router2.vm.box = "generic/ubuntu2204"
        router2.vm.network "private_network", ip: "192.168.56.11"
        router2.vm.hostname = "router2"
        router2.vm.provision "shell", inline: <<-SHELL
        # Disable systemd-resolved and set static DNS
        sudo systemctl disable systemd-resolved
        sudo systemctl stop systemd-resolved
        sudo rm /etc/resolv.conf
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
    
        # Install FRR
        sudo apt-get update
        sudo apt-get install -y frr frr-doc
        sudo sysctl -w net.ipv4.ip_forward=1
        echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
        SHELL
    
        # router1.vm.synced_folder "./config/router1/etc/frr", "/etc/frr"
    
        router2.vm.provision "shell", inline: <<-SHELL

            sudo tee /etc/frr/frr.conf <<EOF
!
frr version 8.1
frr defaults traditional
hostname router2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65002
    bgp router-id 192.168.56.11
    neighbor 192.168.56.10 remote-as 65001
    !
    address-family ipv4 unicast
    network 192.168.56.0/24
    neighbor 192.168.56.10 soft-reconfiguration inbound
    exit-address-family
exit
!
end
EOF

            # Enable BGPD and restart FRR
            sudo sed -i 's/bgpd=no/bgpd=yes/' /etc/frr/daemons
            sudo systemctl restart frr
            # Check if FRR is active
            if ! systemctl is-active --quiet frr; then
                echo "FRR service did not start properly."
                exit 1
            fi
        SHELL
    
    end
  end
  