
RAM = 1000
VCPUS = 2

Vagrant.configure("2") do |config|

    vm_memory = ENV['VM_MEMORY'] || RAM
    vm_cpus = ENV['VM_CPUS'] || VCPUS

    # Configure dc1gw
    config.vm.define "dc1gw" do |dc1gw|
        dc1gw.vm.provider "virtualbox" do |v|
            v.memory = RAM
            v.cpus = VCPUS
        end
        dc1gw.vm.box = "generic/ubuntu2204"
        dc1gw.vm.network "private_network", ip: "192.168.56.10"
        dc1gw.vm.hostname = "dc1gw"
        dc1gw.vm.synced_folder "./dc1gw", "/vagrant"
    
        dc1gw.vm.provision "shell", inline: <<-SHELL
            # Disable systemd-resolved and set static DNS
            sudo systemctl disable systemd-resolved
            sudo systemctl stop systemd-resolved
            sudo rm /etc/resolv.conf
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        
            # Install FRR
            sudo apt-get update
            sudo apt-get install -y frr frr-doc
            sudo sysctl -w net.ipv4.ip_forward=1
            echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
        SHELL
    
        dc1gw.vm.provision "shell", inline: <<-SHELL
            sudo cp /vagrant/etc/frr.conf /etc/frr/frr.conf
            sudo sed -i 's/bgpd=no/bgpd=yes/' /etc/frr/daemons
            sudo systemctl restart frr
            sudo vtysh -c 'show running-config'
        SHELL

    end
  
  
    # Configure dc2gw
    config.vm.define "dc2gw" do |dc2gw|
        dc2gw.vm.provider "virtualbox" do |v|
            v.memory = RAM
            v.cpus = VCPUS
        end
        dc2gw.vm.box = "generic/ubuntu2204"
        dc2gw.vm.network "private_network", ip: "192.168.56.11"
        dc2gw.vm.hostname = "dc2gw"
        dc2gw.vm.synced_folder "./dc2gw", "/vagrant"
    
        dc2gw.vm.provision "shell", inline: <<-SHELL
            # Disable systemd-resolved and set static DNS
            sudo systemctl disable systemd-resolved
            sudo systemctl stop systemd-resolved
            sudo rm /etc/resolv.conf
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        
            # Install FRR
            sudo apt-get update
            sudo apt-get install -y frr frr-doc
            sudo sysctl -w net.ipv4.ip_forward=1
            echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
        SHELL
    
        dc2gw.vm.provision "shell", inline: <<-SHELL
            sudo cp /vagrant/etc/frr.conf /etc/frr/frr.conf
            sudo sed -i 's/bgpd=no/bgpd=yes/' /etc/frr/daemons
            sudo systemctl restart frr
            sudo vtysh -c 'show running-config'
        SHELL

    end

end
  