RAM = 1000
VCPUS = 2

Vagrant.configure("2") do |config|

    vm_memory = ENV['VM_MEMORY'] || RAM
    vm_cpus = ENV['VM_CPUS'] || VCPUS

    config.vm.define "ce1" do |ce1|
        config.vm.box = "briantsaunders/frrouting-stable-7.0"
    end
    config.vm.define "rt1" do |rt1|
        config.vm.box = "briantsaunders/frrouting-stable-7.0"
    end
    config.vm.define "rt2" do |rt2|
        config.vm.box = "briantsaunders/frrouting-stable-7.0"
    end
    config.vm.define "rt3" do |rt3|
        config.vm.box = "briantsaunders/frrouting-stable-7.0"
    end
    config.vm.define "ce2" do |ce2|
        config.vm.box = "briantsaunders/frrouting-stable-7.0"
    end

end